---
abstract: 'DBIC statistics in a table'
author:
  - 'Sebastian Willert, C<willert@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Storage-Statistics-SimpleTable
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08
  MRO::Compat: 0
  Text::SimpleTable: 0
  perl: 5.8.5
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01_01
